CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    type VARCHAR(30) NOT NULL,
    rule_value NUMERIC(19, 2) NOT NULL CHECK (rule_value > 0),
    minimum_order_amount NUMERIC(19, 2) NOT NULL DEFAULT 0 CHECK (minimum_order_amount >= 0),
    stackable BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

ALTER TABLE orders ADD COLUMN subtotal_amount NUMERIC(19, 2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN discount_amount NUMERIC(19, 2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN promotion_codes VARCHAR(500);

UPDATE orders SET subtotal_amount = total_amount WHERE subtotal_amount = 0;
