CREATE TABLE loyalty_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    sub_order_id UUID NOT NULL REFERENCES sub_orders(id),
    type VARCHAR(20) NOT NULL,
    points INTEGER NOT NULL,
    description VARCHAR(250) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_loyalty_sub_order_type UNIQUE (sub_order_id, type)
);

CREATE INDEX idx_loyalty_ledger_customer_id ON loyalty_ledger_entries (customer_id);
