CREATE TABLE stock_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_code VARCHAR(36) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    released_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_stock_reservations_expiry ON stock_reservations(status, expires_at);
CREATE INDEX idx_stock_reservations_user_id ON stock_reservations(user_id);
